# EXAMPLE:
# git tag 0.7.12
# git push origin main
# git push origin 0.7.12
name: Build and Release fade-compendiums

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare release zip
        run: |
          zip -r fade-compendiums.zip ./* -x '.git*' -x '.github/*'

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: fade-compendiums.zip
          token: ${{ secrets.GITHUB_TOKEN }}

